---
title: "Presentations"
---

## International conferences

```{r}
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(gt)
library(glue)
library(lubridate)
talks <- read_csv("talksInt.csv")
talks <- talks |>
  mutate(Date = dmy(Date)) |>
  mutate(eventlink = ifelse(is.na(Link), Event, glue("[{Event}]({Link})"))) 
talks |>
  arrange(desc(Date)) |>
  select(Date, Title, eventlink, Location, Presentation, Contribution) |>
  gt() |>
    gt::fmt_markdown(columns = c(Title, eventlink)) |>
    cols_label(eventlink = "Event") |> 
    gt::cols_width(
      Date ~ px(100),
      Title ~ px(400),
      eventlink ~ px(400),
      Location ~ px(250),
      Presentation ~ px(100),
      Contribution ~ px(100)) |>
  cols_align("left")
```

## Local conferences

```{r}
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(gt)
library(glue)
library(lubridate)
talks <- read_csv("talksSA.csv")
talks <- talks |>
  mutate(Date = dmy(Date),
  eventlink = ifelse(is.na(Link), Event, glue("[{Event}]({Link})"))) 
talks |>
  arrange(desc(Date)) |>
  select(Date, Title, eventlink, Host, Presentation, Contribution) |>
  gt() |>
    gt::fmt_markdown(columns = c(Title, eventlink)) |>
    cols_label(eventlink = "Event") |> 
    gt::cols_width(
      Date ~ px(100),
      Title ~ px(400),
      eventlink ~ px(400),
      Host ~ px(250),
      Presentation ~ px(100),
      Contribution ~ px(100)) |>
  cols_align("left")
```

## Seminars and workshops

```{r}
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(gt)
library(glue)
library(lubridate)
talks <- read_csv("seminars.csv")
talks <- talks |>
  mutate(Date = dmy(Date)) |>
  mutate(presentationlink = ifelse(is.na(Link), Presentation, glue("[{Presentation}]({Link})"))) 
talks |>
  arrange(desc(Date)) |>
  select(Date, Title, Event, Location, presentationlink) |>
  gt() |>
    gt::fmt_markdown(columns = c(Title, presentationlink)) |>
    cols_label(presentationlink = "Presentation") |> 
    gt::cols_width(
      Date ~ px(100),
      Title ~ px(400),
      Event ~ px(400),
      Location ~ px(250),
      presentationlink ~ px(100)) |>
  cols_align("left")
```
